version: '3.1'
services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    container_name: postgresprisma
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=livestream
    ports:
      - 5432:5432
    volumes:
      - docker-postgres:/var/lib/postgresql/data
    networks:
      - livestream-app
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:randompassword@postgres:5432/livestream?schema=public
      - ACCESSTOKENCLOUD=312|XpS4bX0TGOCesP42zwwXOwY4Gus7i2PJn4BK7C80
      - GOOGLE_CLIENT_ID=1021811593879-a4f0h767bd6s13bt1ei910beqepp3qmc.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      - CALLBACK_GOOGLE_URL=http://localhost:4000/api/v1/auth/google/callback
      - FACEBOOK_CLIENT_ID=1425041068343175
      - FACEBOOK_SECRET=ead916b4ab4fd6025df7ea88d4a29406
      - CALLBACK_FACEBOOK_URL=http://localhost:4000/api/v1/auth/facebook/callback
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/src
    ports:
      - 4000:4000
    depends_on:
      - postgres
    networks:
      - livestream-app
networks:
  livestream-app:
    driver: bridge
volumes:
  docker-postgres:
