version: '3'
services:
  db:
    image: postgres:13.5
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = randompassword
      - POSTGRES_DB = livestream
      - POSTGRES_HOST_AUTH_METHOD=trust
