version: '3'
services:
  db:
    image: postgres:12-alpine
    restart: always
    container_name: postgresprisma
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=livestream
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '4000:4000'
  #   depends_on:
  #     - db
