version: '3.1'
services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    container_name: postgresprisma
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=livestream
    ports:
      - 5432:5432
    volumes:
      - docker-postgres:/var/lib/postgresql/data
volumes:
  docker-postgres:
